# Generated by Django 5.1.7 on 2025-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparereport',
            name='failing',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='comparereport',
            name='passing',
            field=models.JSONField(default=list),
        ),
    ]
