# Generated by Django 5.2b1 on 2025-03-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='applicant_resume',
            new_name='resume',
        ),
        migrations.AddField(
            model_name='report',
            name='job_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
