# Generated by Django 5.1.7 on 2025-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='education_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experience_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
