# Generated by Django 5.2b1 on 2025-03-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_applicant_resume_report_resume_report_job_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='CompareReport',
        ),
    ]
