# Generated by Django 5.1.6 on 2025-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='applicant_name',
        ),
        migrations.AddField(
            model_name='report',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
