# Generated by Django 5.1.7 on 2025-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comparereport_failing_comparereport_passing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparereport',
            name='applicant_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comparereport',
            name='applicant_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
