# Generated by Django 5.1.6 on 2025-03-05 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_report_applicant_name_report_passed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('remote', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='applicant_resume',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
