services:
  backend:
    build:
      context: ./ResumeComparatorBackend
      dockerfile: Dockerfile
    volumes:
      - ./ResumeComparatorBackend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./resume_comparator_frontend
      dockerfile: Dockerfile
    volumes:
      - ./resume_comparator_frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0